### ISSUE TITLE
Clean up the deployment names and labels

### ISSUE THREAD

**Issue by djfarrelly** [bufferapp/buffer-publish#84]
### Idea
Instead of the k8s deployment name and label being `master-buffer-publish-buffer-publish` can we make it `buffer-publish` or `buffer-publish-app` then make the labels:

```yaml
labels:
  app: publish
  service: app
  track: stable
```

Additionally it would be great to change the names of the branch deploys from:
```
task-app-sidebar-fetch-data-buffer-publish-buffer-publish
```
To a left-most-namespace like
```
buffer-publish-task-app-sidebar-fetch-data
```

Also to better leverage the filtering and organizational features of k8s labels, can we change them to:
```yaml
labels:
  app: publish
  service: app
  track: staging
  branch: task-app-sidebar-fetch-data
```
This way we can filter on our pods quickly like `k get po -l app=publish -l track=staging`

What do you think @stevenc81?
